version: "3.3"
services:
  app:
    build: .
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWD: example
      POSTGRES_HOST: db
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    image: postgres:alpine3.15
    environment:
      POSTGRES_PASSWORD: example
