version: "3.9"
x-backend: &backend
  build: .
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWD: example
    POSTGRES_HOST: db
    REDIS_URL: redis://redis:6379/
  depends_on:
    db:
      condition: service_healthy
    redis:
      condition: service_healthy

services:
  app:
    <<: *backend
    ports:
      - 3000:3000

  cron:
    <<: *backend
    entrypoint: /bin/sh -c "whenever --update-crontab && crond -f"

  sidekiq:
    <<: *backend
    command: sidekiq -r ./config/application.rb

  db:
    image: postgres:alpine3.15
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /var/lib/postgresql/data/
    volumes:
      - ./tmp/db:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    volumes:
      - ./tmp/redis:/data
    ports:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 5s
      timeout: 5s
      retries: 5
